Window.SetBackgroundTopColor(1,2,1);
Window.SetBackgroundBottomColor(0,0,0);

for(i=1;i<=6;i++)
	Wabby[i-1]=Image("wabby-0"+i+".png");
	WabbyS= Sprite();
	i=1;
	

fun refresh(){
    /*
    @Funcion: refresh
    @Argumentos:None

    @Retorno:None
    @Descripcion:esta funcion refresca el muestra el plymouth con wabby
    */
    WabbyS.SetImage(Wabby[Math.Int(i)]);
    if(i>6)
	i=1;
    else
    i+=0.3;
    
}
refresh();
Plymouth.SetRefreshFunction(refresh);
status="normal";